name: 'shop'

services:

  user-context:
    image: ${USER_CONTEXT_DOCKER_IMAGE}
    ports:
      - ${USER_CONTEXT_PORTS}:${USER_CONTEXT_PORTS}
    environment:
      SPRING_APPLICATION_NAME: ${USER_CONTEXT_APPLICATION_NAME}
    extends:
      service: common-apps
      file: common.yml

networks:
  shop-network:
    driver: bridge